// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2jq2fNU1EWO7mOFehXFVlQJM28XXXMvE',
    appId: '1:465245524520:web:e4da15dd0b0f67748d1b1d',
    messagingSenderId: '465245524520',
    projectId: 'grocerease-d83e0',
    authDomain: 'grocerease-d83e0.firebaseapp.com',
    storageBucket: 'grocerease-d83e0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATiIItu0Wg1qsLQIE32ED1G2DQJoQHN6M',
    appId: '1:465245524520:android:27e69fc706c786338d1b1d',
    messagingSenderId: '465245524520',
    projectId: 'grocerease-d83e0',
    storageBucket: 'grocerease-d83e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkvOKySQoxKLLFNGLpQHogewqx-9A24tQ',
    appId: '1:465245524520:ios:a00b2bfed1cd25c18d1b1d',
    messagingSenderId: '465245524520',
    projectId: 'grocerease-d83e0',
    storageBucket: 'grocerease-d83e0.appspot.com',
    iosBundleId: 'com.example.grocerEase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkvOKySQoxKLLFNGLpQHogewqx-9A24tQ',
    appId: '1:465245524520:ios:3b9b1b969d5e1cca8d1b1d',
    messagingSenderId: '465245524520',
    projectId: 'grocerease-d83e0',
    storageBucket: 'grocerease-d83e0.appspot.com',
    iosBundleId: 'com.example.grocerEase.RunnerTests',
  );
}
